### PR TITLE
Configured RockLib.Collections GitHub Actions CI/CD Pipeline

### PR DESCRIPTION
**Pull request by eslutz**
## Description

Moved from AppVeyor for workflows to GitHub Actions.

#### Build and test code when a pull request is created or commits added to request
- Solution is built and unit tests are run
  - Fails the workflow if any unit test fails

#### Build, test, and publish package when a GitHub Release is created (workflow trigger on GitHub release still needs to be tested)
- Solution is built and unit tests are run
  - Fails the workflow if any unit test fails
- Checks for projects where csproj file has been changed
  - Gets all changed files from current commit on main compared to last commit on main
  - Filters changed filed to only csproj files
    - Excluded test projects that follow the `.Tests.csproj` naming convention
    - Excludes example projects that start with the `Example.` naming convention
  - Fails the workflow if there are no files left after filtering
- Approval step required for each package to be published
- Once approved, project is packed and published to NuGet

#### Successfully tested Build and Test [workflow](https://github.com/RockLib/RockLib.Collections/actions/runs/2862633511)
image

#### Successfully tested Build and Test workflow runs on opening PR and subsequent commits to branch
image

#### Successfully tested Build and Publish [workflow](https://github.com/RockLib/RockLib.Collections/actions/runs/2862573283)
image

#### Successfully published package to [NuGet](https://www.nuget.org/packages/RockLib.Collections/)
image

## Type of change: 

Updates to CI/CD pipeline.

---

<sup>_[Reviewer guidelines](../blob/main/CONTRIBUTING.md#reviewing-changes)_</sup>

### CODE REVIEW

**Comment by NeilSchiefer** [comment]
I think this looks ok as far as I can tell at the moment.:)  Could we document how the github actions technically does stuff?  Or could we add comments in the action configs to highlight more what the actions are doing?  This would be just once so we can get a better handle on how this is all working.

**Comment by eslutz** [comment]
> I think this looks ok as far as I can tell at the moment.:) Could we document how the github actions technically does stuff? Or could we add comments in the action configs to highlight more what the actions are doing? This would be just once so we can get a better handle on how this is all working.

Yes, that's a good callout.  I'll add some additional comments to make clear what each part of the workflow is doing.

**Comment by kristycurrier** [comment]
Great job @eslutz and @JacobStade1 !

**Comment by NeilSchiefer** [comment]
> Great job @eslutz and @JacobStade1 !

Yep this is great stuff thanks!

**Review by NeilSchiefer — APPROVED** [review]

**Review by JacobStade1 — APPROVED** [review]

**Pull request merged**
